[[main]]
  identifier = "about"
  name = "ğŸ‘¨â€ğŸ’» About"
  url = "/about/"
  weight = 1

[[main]]
  identifier = "posts"
  name = "ğŸ“ Posts"
  url = "/posts/"
  weight = 2

[[main]]
  identifier = "tils"
  name = "ğŸ”¥ TIL"
  url = "/TIL/docs/"
  weight = 2
