[[main]]
  identifier = "about"
  name = "ğŸ“– About"
  url = "/about/"
  weight = 1

[[main]]
  identifier = "resume"
  name = "ğŸ‘¨â€ğŸ’» Resume"
  url = "/resume/"
  weight = 2

[[main]]
  identifier = "posts"
  name = "ğŸ“ Posts"
  url = "/posts/"
  weight = 3

[[main]]
  identifier = "tils"
  name = "ğŸ”¥ TIL"
  url = "/TIL/docs/"
  weight = 4
